import type { LessonGenerationSource, LessonPlan, StructuredLessonDraft } from '@/app/core/types/lessonPlans';

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

function stringList(value: unknown): string[] {
  return Array.isArray(value)
    ? value.map((item) => String(item ?? '').trim()).filter(Boolean)
    : [];
}

function numberList(value: unknown): number[] {
  return Array.isArray(value)
    ? value.map((item) => Number(item)).filter((item) => Number.isInteger(item))
    : [];
}

export function getStructuredLessonDraft(lessonPlan: LessonPlan): StructuredLessonDraft | null {
  const snapshot = lessonPlan.generated_draft_snapshot;
  if (!isRecord(snapshot)) {
    return null;
  }
  const rawDraft = snapshot.structured_draft;
  if (!isRecord(rawDraft)) {
    return null;
  }
  const rawPhases = Array.isArray(rawDraft.phases) ? rawDraft.phases : [];
  const phases = rawPhases.filter(isRecord).map((phase) => ({
    phase_type: String(phase.phase_type ?? ''),
    title: String(phase.title ?? ''),
    duration_minutes: Number(phase.duration_minutes ?? 0),
    teacher_actions: stringList(phase.teacher_actions),
    learner_actions: stringList(phase.learner_actions),
    resources: stringList(phase.resources),
    assessment_checks: stringList(phase.assessment_checks),
    evidence_expected: stringList(phase.evidence_expected),
  }));
  if (phases.length === 0) {
    return null;
  }
  const differentiation = isRecord(rawDraft.differentiation) ? rawDraft.differentiation : {};
  const conclusion = isRecord(rawDraft.conclusion) ? rawDraft.conclusion : {};
  const objectives = (Array.isArray(rawDraft.objectives) ? rawDraft.objectives : [])
    .filter(isRecord)
    .map((objective) => ({
      text: String(objective.text ?? '').trim(),
      source_outcome_ids: numberList(objective.source_outcome_ids),
    }))
    .filter((objective) => objective.text);

  return {
    title: String(rawDraft.title ?? lessonPlan.title ?? '').trim(),
    objectives,
    prior_knowledge: String(rawDraft.prior_knowledge ?? '').trim(),
    learning_resources: stringList(rawDraft.learning_resources),
    phases,
    differentiation: {
      support: stringList(differentiation.support),
      extension: stringList(differentiation.extension),
    },
    conclusion: {
      teacher_actions: stringList(conclusion.teacher_actions),
      learner_actions: stringList(conclusion.learner_actions),
      exit_evidence: stringList(conclusion.exit_evidence),
    },
    selected_reference_entry_ids: numberList(rawDraft.selected_reference_entry_ids),
  };
}

export function getLessonGenerationSource(lessonPlan: LessonPlan): LessonGenerationSource {
  const context = lessonPlan.generated_context;
  if (isRecord(context)) {
    const generation = context.generation;
    if (isRecord(generation)) {
      const source = String(generation.generation_source ?? '');
      if (source === 'ai' || source === 'ai_repaired' || source === 'fallback') {
        return source;
      }
    }
    const source = String(context.generation_source ?? '');
    if (source === 'ai' || source === 'ai_repaired' || source === 'fallback') {
      return source;
    }
  }
  if (lessonPlan.generated_by_ai) {
    return 'ai';
  }
  if (lessonPlan.ai_fallback_reason?.trim()) {
    return 'fallback';
  }
  return lessonPlan.generated_at ? 'rule-based' : 'unknown';
}

export function getLessonGenerationBadge(lessonPlan: LessonPlan): {
  label: string;
  description: string;
  tone: 'purple' | 'green' | 'amber' | 'gray';
  source: LessonGenerationSource;
} {
  const source = getLessonGenerationSource(lessonPlan);
  if (source === 'ai') {
    return {
      source,
      label: 'AI-assisted draft',
      description: 'Generated by AI within Scholaroscope curriculum constraints.',
      tone: 'purple',
    };
  }
  if (source === 'ai_repaired') {
    return {
      source,
      label: 'AI-assisted draft · validated',
      description: 'Generated by AI and repaired once to satisfy Scholaroscope validation.',
      tone: 'green',
    };
  }
  if (source === 'fallback') {
    return {
      source,
      label: 'Basic draft',
      description: 'AI assistance was unavailable or could not produce a valid draft. Scholaroscope created a safe curriculum-based draft instead.',
      tone: 'amber',
    };
  }
  if (source === 'rule-based') {
    return {
      source,
      label: 'Rule-based draft',
      description: 'Generated from selected outcomes and references without AI assistance.',
      tone: 'gray',
    };
  }
  return {
    source,
    label: 'Draft',
    description: 'Lesson preparation draft.',
    tone: 'gray',
  };
}

export function containsInternalCurriculumIdentifier(value: string): boolean {
  return /\b[A-Za-z_]+\.grade\d+[A-Za-z0-9_.-]*\b/i.test(value);
}
