export const themeClasses = {
  pageShell: 'space-y-6',
  card: 'theme-card rounded-2xl',
  mutedCard: 'theme-card-muted rounded-2xl',
  elevatedSurface: 'theme-surface-elevated rounded-2xl',
  dropdown: 'theme-dropdown rounded-xl',
  infoSurface: 'theme-info-surface rounded-2xl',
  warningSurface: 'theme-warning-surface rounded-2xl',
  dangerSurface: 'theme-danger-surface rounded-2xl',
  selectedSurface: 'theme-info-surface-strong rounded-2xl',
  label: 'mb-1 block text-sm font-medium theme-text',
  helperText: 'text-xs theme-subtle',
  interactiveSurface: 'theme-hover-surface',
  interactiveBorder: 'theme-hover-border-strong',
  checkbox: 'theme-checkbox',
  authPage: 'relative min-h-screen overflow-hidden px-4 py-10 sm:px-6 lg:px-8',
  authShell: 'relative z-10 mx-auto w-full max-w-md space-y-6',
  authCard: 'theme-card rounded-2xl p-8',
  settingsSection: 'space-y-4',
  dashboardCard: 'theme-card rounded-2xl shadow-[var(--shadow-soft)]',
  dashboardPanel: 'theme-surface-elevated rounded-xl border theme-border shadow-[var(--shadow-soft)]',
  dashboardMutedPanel: 'theme-surface-muted rounded-xl border theme-border',
  dashboardMetricCard: 'theme-surface-elevated rounded-2xl border theme-border shadow-[var(--shadow-soft)]',
  dashboardActionRow: 'theme-surface-muted rounded-xl border theme-border theme-hover-surface theme-hover-border-strong',
  dashboardIconTile: 'rounded-xl shadow-lg',
  dashboardLink: 'theme-link font-semibold transition-colors',
  dashboardStatusSurface: 'theme-surface-muted rounded-full border theme-border',
} as const;
