// ============================================================================
// app/types/organization.ts
// Mirrors: apps/core/models.py Organization + OrganizationSerializer
// ============================================================================

export type PlanType = 'FREE' | 'BASIC' | 'PREMIUM' | 'ENTERPRISE';

export interface Organization {
    id: number;
    name: string;
    slug: string;
    code: string;
    email: string;
    phone: string;
    address: string;
    logo: string;
    is_active: boolean;
    plan_type: PlanType;
    user_count: number;        // SerializerMethodField (read-only)
    created_at: string;
    updated_at: string;
}

// Used for Create form (slug + code are auto-generated by backend)
export interface OrganizationCreatePayload {
    name: string;
    email?: string;
    phone?: string;
    address?: string;
    logo?: string;
    plan_type?: PlanType;
}

// Used for Edit form (same writable fields)
export interface OrganizationUpdatePayload {
    name?: string;
    email?: string;
    phone?: string;
    address?: string;
    logo?: string;
    plan_type?: PlanType;
    is_active?: boolean;
}

// From GET /api/organizations/{id}/statistics/
export interface OrganizationStats {
    total_users: number;
    active_users: number;
    by_role: {
        admins: number;
        instructors: number;
    };
}

// From GET /api/organizations/{id}/users/
export interface OrgUser {
    id: number;
    email: string;
    first_name: string;
    last_name: string;
    full_name: string;
    role: 'ADMIN' | 'INSTRUCTOR';
    role_display: string;
    is_active: boolean;
    phone: string;
    date_joined: string;
    last_login: string | null;
}

export const PLAN_LABELS: Record<PlanType, string> = {
    FREE: 'Free',
    BASIC: 'Basic',
    PREMIUM: 'Premium',
    ENTERPRISE: 'Enterprise',
};

export const PLAN_COLORS: Record<PlanType, 'default' | 'info' | 'purple' | 'orange'> = {
    FREE: 'default',
    BASIC: 'info',
    PREMIUM: 'purple',
    ENTERPRISE: 'orange',
};